# Generated by Django 4.2.7 on 2024-01-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('M', 'mobile'), ('L', 'Laptop'), ('BW', 'Bottom wear'), ('TW', 'Top wear'), ('LS', 'Ladies')], max_length=3),
        ),
    ]
