# Generated by Django 4.2.7 on 2024-02-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('M', 'mobile'), ('L', 'Laptop'), ('BW', 'Bottom wear'), ('TW', 'Top wear'), ('LS', 'Ladies'), ('LB', 'Ladies Bottomwear')], max_length=3),
        ),
    ]
